name: Verify distributed dependencies

on:
  push:
    branches:
      - tms-dependency-admin_*
    paths:
      - buildSrc/src/main/kotlin/default/dependencies.kt
      - buildSrc/src/main/kotlin/groups.kt
jobs:
  check-validity-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sjekk ut branch'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2

      - name: 'Bygg og kjør tester for å sjekke at nye versjoner er kompatible'
        run: |
          ./gradlew clean build

      - name: 'Merge kode fra branch og push til main'
        run: |
          git fetch
          git checkout main
          git merge ${{ github.ref_name }}
          git push
          git push origin --delete ${{ github.ref_name }}

  open-pull-request-if-failed:
    needs: check-validity-and-merge
    if: always() && needs.check-validity-and-merge.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: 'Åpner PR for manuell behandling'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const branch = context.ref;
            const result = await github.rest.pulls.create({
              title: 'Dependencies - manuelle endringer kreves',
              owner,
              repo,
              head: branch,
              base: 'main',
              body: 'Nye versjoner av dependencies krever manuell behandling'
            });
