name: Publiser default depdendency config

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to update'
        required: true
        type: string

env:
  DRY_RUN: ${{ github.event.client_payload.dry_run }}

jobs:
  build-and-publish-on-main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update remote workflow
        run: |
          cd ./script
          ./distribute_workflows.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          INCLUDE: ${{ inputs.repository }}

      - name: Distribute dependencies
        run: |
          cd ./script
          ./distribute_default_dependencies.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          INCLUDE: ${{ inputs.repository }}
