name: Publiser til bestemt repo

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to update'
        required: true
        type: string

jobs:
  publish-dependencies-to-requested-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate token
        run: |
          ./script/validate_token.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}

      - name: Validate remote dependency and setup env
        run: |
          ./script/setup_repository.sh
        env:
          MANAGED_APP: ${{ inputs.repository }}
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}

      - name: Update remote workflow
        run: |
          ./script/push_workflow.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          REPOSITORY: ${{ env.REPOSITORY }}
          MAIN_BRANCH: ${{ env.MAIN_BRANCH }}
          LATEST_COMMIT_SHA: ${{ env.LATEST_COMMIT_SHA }}

      - name: Distribute dependencies
        run: |
          ./script/push_default_dependencies.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          REPOSITORY: ${{ env.REPOSITORY }}
          MAIN_BRANCH: ${{ env.MAIN_BRANCH }}
          LATEST_COMMIT_SHA: ${{ env.LATEST_COMMIT_SHA }}
