name: Vulnerabilities scanning of dependencies
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  Vulnerability_scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk for gradle to check for vulnerabilities
        uses: snyk/actions/gradle-jdk14@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --org=min-side --configuration-attributes=usage:java-runtime --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git
